export const pictoSongs = `{"Swoon.EXE": {"track": "Swoon.EXE", "game": "Super Paper Mario", "url": "https://www.youtube.com/embed/pUb04A02H9A?si=Ls6MHLK0e5o80p1frel=0&enablejsapi=1", "from": "Picto"}, 
"Main Theme": {"track": "Main Theme", "game": "Paper Mario: The Thousand-Year Door", "url": "https://www.youtube.com/embed/g85qitETTlI?si=-Ghd3t25qR5bQ3pXrel=0&enablejsapi=1", "from": "Picto"},
"Toxic Caves": {"track": "Toxic Caves", "game": "Sonic The Hedgehog Spinball", "url": "https://www.youtube.com/embed/BXisDB21XKY?si=IaGybQ1EimI-HD34rel=0&enablejsapi=1", "from": "picto"},
"Monkey Target 2": {"track": "Monkey Target 2", "game": "Super Monkey Ball 2", "url": "https://www.youtube.com/embed/mCVI95S1t9M?si=fv2bZ_cbIGPqGZrnrel=0&enablejsapi=1"},
"Yoga": {"track": "Yoga", "game": "Wii Fit", "url": "https://www.youtube.com/embed/RZFhVs6OGAc?si=QNOGsJBviWUplMjarel=0&enablejsapi=1"},
"Knitty Knotty Windmill": {"track": "Knitty Knotty Windmill", "game": "Yoshi's Woolly World", "url": "https://www.youtube.com/embed/SlrWvPWR890?si=648mGb0zSN5watNDrel=0&enablejsapi=1"},
"Title Screen": {"track": "Title Screen", "game": "Animal Crossing: Wild World", "url": "https://www.youtube.com/embed/OM33TiQKl7I?si=lBDwvztMByq8tDwKrel=0&enablejsapi=1"},
"Speak Your Mind": {"track": "Speak Your Mind", "game": "Tales of Graces f", "url": "https://www.youtube.com/embed/Gk2_hfAbcfs?si=kiCcBr7FCorPLLFvrel=0&enablejsapi=1"},
"Route 113": {"track": "Route 113", "game": "Pokemon Ruby", "url": "https://www.youtube.com/embed/wfARFF9S5Jg?si=ZCxo7Tm5nSTXOsonrel=0&enablejsapi=1"},
"Nighttime (Globe)": {"track": "Nighttime (Globe)", "game": "Wii Forecast Channel", "url": "https://www.youtube.com/embed/GLDhvJ0fmAw?si=rWlZdmburl2y24e9rel=0&enablejsapi=1"},
"Tip Cat": {"track": "Tip Cat", "game": "Wii News Channel", "url": "https://www.youtube.com/embed/DD8A3__H6rU?si=BfTBDYoQ8y4fhLLyrel=0&enablejsapi=1"},
"5AM": {"track": "5AM", "game": "Animal Crossing: City Folk", "url": "https://www.youtube.com/embed/ptNHL_v1BLI?si=P2G0Lpx4kErG7Lxprel=0&enablejsapi=1"},
"Mii Maker": {"track": "Mii Maker", "game": "Tomodachi Life", "url": "https://www.youtube.com/embed/x81tdSjUd1A?si=0YI4eDNmrAvTuuqZrel=0&enablejsapi=1"},
"Jungle Island": {"track": "Jungle Island", "game": "Super Monkey Ball 2", "url": "https://www.youtube.com/embed/4_XAkfr0WHY?si=DxBMAPgn5H8HUFnQrel=0&enablejsapi=1"},
"Inside the Whale": {"track": "Inside the Whale", "game": "Super Monkey Ball 2", "url": "https://www.youtube.com/embed/WOiNvMSJ7EQ?si=C7We5bQN9ALv6ZcUrel=0&enablejsapi=1"},
"Monkey Billiards 2": {"track": "Monkey Billiards 2", "game": "Super Monkey Ball 2", "url": "https://www.youtube.com/embed/l14iNKitF0Y?si=rlN6aekgdjtGfPOerel=0&enablejsapi=1"},
"Monkey Bowling 2": {"track": "Monkey Bowling 2", "game": "Super Monkey Ball 2", "url": "https://www.youtube.com/embed/EzUUoHQLS5k?si=ZZHv1xrGUri-wUEJrel=0&enablejsapi=1"},
"Main Theme": {"track": "Main Theme", "game": "Mario Paint", "url": "https://www.youtube.com/embed/0GdapZ1FZhI?si=T8569jolb87g96BKrel=0&enablejsapi=1"},
"Creative Exercise": {"track": "Creative Exercise", "game": "Mario Paint", "url": "https://www.youtube.com/embed/6j0HiMpV1HE?si=zk_AsEjFyllFHUIKrel=0&enablejsapi=1"},
"Escape From the City": {"track": "Escape From the City", "game": "Sonic Adventure 2", "url": "https://www.youtube.com/embed/5WcyVvWZJU4?si=ywNjgY3lFZeyTCmIrel=0&enablejsapi=1"},
"Chao Garden": {"track": "Chao Garden", "game": "Sonic Adventure 2", "url": "https://www.youtube.com/embed/IaB7M1T6jUk?si=MzWS6bSwxroLFTjLrel=0&enablejsapi=1"},
"Chao Kindergarten": {"track": "Chao Kindergarten", "game": "Sonic Adventure 2", "url": "https://www.youtube.com/embed/Yo2XPnAQxl0?si=gxpG9XGQKwGDKoiorel=0&enablejsapi=1"},
"Main Menu": {"track": "Main Menu", "game": "Mario Golf: Toadstool Tour", "url": "https://www.youtube.com/embed/90SMvqwxrE8?si=JimOxANtqli6q6dwrel=0&enablejsapi=1"},
"Peach's Castle Grounds": {"track": "Peach's Castle Grounds", "game": "Mario Golf: Toadstool Tour", "url": "https://www.youtube.com/embed/MZDrmnRjLwU?si=LJFmOIIjhIeya0farel=0&enablejsapi=1"},
"Level Select": {"track": "Level Select", "game": "Wario Ware: Smooth Moves", "url": "https://www.youtube.com/embed/pZ2Y98ZRxyA?si=eibooEvNtNavF4rxrel=0&enablejsapi=1"},
"Card Party": {"track": "Card Party", "game": "Mario Party 5", "url": "https://www.youtube.com/embed/iQ-LO0IoeqQ?si=FWPR8Lb_ROPfUzxarel=0&enablejsapi=1"},
"Dream Memories": {"track": "Dream Memories", "game": "Mario Party 5", "url": "https://www.youtube.com/embed/ra5U1Acm-xA?si=Jvye-a_o1Mqf6hiYrel=0&enablejsapi=1"},
"Pick the Rules": {"track": "Pick the Rules", "game": "Mario Party 8", "url": "https://www.youtube.com/embed/U1sYDWzhEog?si=AfSmAJocHktXE9A6rel=0&enablejsapi=1"},
"The Tricky Stuff": {"track": "The Tricky Stuff", "game": "Kirby's Dream Course", "url": "https://www.youtube.com/embed/F_6CKgo8Fyo?si=upbK-qQ_XGI4_bN6rel=0&enablejsapi=1"},
"Welcome to Station Square": {"track": "Welcome to Station Square", "game": "Sonic Adventure", "url": "https://www.youtube.com/embed/dWbSg0VOSgg?si=gZWSVLAO6SXUvwl8rel=0&enablejsapi=1"},
"Bright Sound": {"track": "Bright Sound", "game": "Sonic Adventure 2", "url": "https://www.youtube.com/embed/-AFil1Vm2KY?si=ykeRH0uQ4KvR5zdorel=0&enablejsapi=1"},
"I'm a Spy": {"track": "I'm a Spy", "game": "Sonic Adventure 2", "url": "https://www.youtube.com/embed/UMsT9om7seE?si=_qjJ9FF_h10c8Ohvrel=0&enablejsapi=1"},
"Dolphin Coast": {"track": "Dolphin Coast", "game": "Petz Dogz 2", "url": "https://www.youtube.com/embed/75uSaRdF1qk?si=oqdyZI-xptzSBaufrel=0&enablejsapi=1"},
"Pawville": {"track": "Pawville", "game": "Petz Dogz 2", "url": "https://www.youtube.com/embed/9Jth2ieP4KU?si=bp1iptg8exzT7OBprel=0&enablejsapi=1"},
"Tank 1": {"track": "Tank 1", "game": "Insaniquarium", "url": "https://www.youtube.com/embed/VxA7-bKCqDw?si=XZvPIQOHEFHcTLcmrel=0&enablejsapi=1"},
"Toad Highlands": {"track": "Toad Highlands", "game": "Mario Golf 64", "url": "https://www.youtube.com/embed/806KyO4lzcU?si=QoT3WFKQ4iDgM-Korel=0&enablejsapi=1"},
"Reception Desk": {"track": "Reception Desk", "game": "Pokemon Battle Revolution", "url": "https://www.youtube.com/embed/xYWSHzKWgGU?si=qe3tXsOp1H1KKXJorel=0&enablejsapi=1"},
"Neon Colosseum": {"track": "Neon Colosseum", "game": "Pokemon Battle Revolution", "url": "https://www.youtube.com/embed/t2Sz_BD2CBA?si=u85E4KYCoZLDZiocrel=0&enablejsapi=1"},
"Title Screen": {"track": "Title Screen", "game": "Animal Crossing", "url": "https://www.youtube.com/embed/MatjRS1zhxI?si=-Zg4hSN-qaCeWQ-mrel=0&enablejsapi=1"},
"Working For Tom Nook": {"track": "Working For Tom Nook", "game": "Animal Crossing", "url": "https://www.youtube.com/embed/2zcECHzNcO8?si=4nI0AFDp8iwBxYAorel=0&enablejsapi=1"},
"K.K.'s Intro": {"track": "K.K.'s Intro", "game": "Animal Crossing", "url": "https://www.youtube.com/embed/zrS2FDcsjZk?si=tAfwQMpc0plXk3gKrel=0&enablejsapi=1"},
"How to Play Minigames": {"track": "How to Play Minigames", "game": "Mario Party 8", "url": "https://www.youtube.com/embed/_yy9gXheUwo?si=83d1HFhPgKOVpJEerel=0&enablejsapi=1"},
"Story of the Thousand-Year Door": {"track": "Story of the Thousand-Year Door", "game": "Paper Mario: The Thousand-Year Door", "url": "https://www.youtube.com/embed/r6ElCq5keUU?si=h6y4iSwib596KIGrrel=0&enablejsapi=1"},
"Meet Professor Frankly": {"track": "Meet Professor Frankly", "game": "Paper Mario: The Thousand-Year Door", "url": "https://www.youtube.com/embed/UP5ehZV9TvQ?si=y2wW0cMRcCPRPk5arel=0&enablejsapi=1"},
"Inn Pre-Sleep": {"track": "Inn Pre-Sleep", "game": "Miitopia", "url": "https://www.youtube.com/embed/cay7JsdH4Lw?si=8Da9BX6x5en9_r1krel=0&enablejsapi=1"},
"Carnival Night Zone (Act 1)": {"track": "Carnival Night Zone (Act 1)", "game": "Sonic the Hedghehog 3", "url": "https://www.youtube.com/embed/dt1e6mBFp4A?si=CwFqqPj78WhBpmt0rel=0&enablejsapi=1"},
"Main Theme": {"track": "Main Theme", "game": "Tetris Attack", "url": "https://www.youtube.com/embed/rDdC8SaB0uA?si=SmCDVvK-47WmLqMfrel=0&enablejsapi=1"},
"Lunar Stage (Raphael the Raven)": {"track": "Lunar Stage (Raphael the Raven)", "game": "Tetris Attack", "url": "https://www.youtube.com/embed/P8K6_GuQTpM?si=9X07wROB7oJ4RnsGrel=0&enablejsapi=1"},
"Shopping Theme": {"track": "Shopping Theme", "game": "Nintendogs", "url": "https://www.youtube.com/embed/aIhB9ZuMg7Y?si=WxiDs8tUrpyXWZDxrel=0&enablejsapi=1"},
"Bath Time": {"track": "Bath Time", "game": "Nintendogs", "url": "https://www.youtube.com/embed/eWB7Cy4zmWM?si=OXlO1waDAQjZPD9Lrel=0&enablejsapi=1"},
"Fight Theme": {"track": "Fight Theme", "game": "Mike Tyson's Punch Out!!", "url": "https://www.youtube.com/embed/VE8vKLEK6A8?si=kuuOO841SyAjUHYgrel=0&enablejsapi=1"}
}`
